spring.application.name=Volunteer_Module
server.port=8082

# --- Database config ---
spring.datasource.url=jdbc:mysql://localhost:3306/relief_sync_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
