spring.application.name=demo
server.port=8084

# --- Gmail Config ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fuyanchia@gmail.com
spring.mail.password=ptnc nrhm qhdq fymw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- RabbitMQ Config ---
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672

# --- Database config ---
spring.datasource.url=jdbc:mysql://mysql-task:3306/relief_sync_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- update use for let spring boot will auto establish database and table
# --- in Mysql based on the Entity coding
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

